
export default function handler(req, res) {
  res.status(200).json(
    [{
      "id": 1,
      "username": "cbeardwell0@ehow.com",
      "otherName": "Carmine",
      "lastName": "Beardwell",
      "avatar": "https://robohash.org/quisimiliquealiquid.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-07-11T16:51:25Z"
    }, {
      "id": 2,
      "username": "jgummary1@macromedia.com",
      "otherName": "Jolynn",
      "lastName": "Gummary",
      "avatar": "https://robohash.org/autemerrorqui.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-09-09T15:38:08Z"
    }, {
      "id": 3,
      "username": "rclifft2@surveymonkey.com",
      "otherName": "Rorie",
      "lastName": "Clifft",
      "avatar": "https://robohash.org/idrerumet.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-08-15T07:09:20Z"
    }, {
      "id": 4,
      "username": "hgosalvez3@cbsnews.com",
      "otherName": "Harlan",
      "lastName": "Gosalvez",
      "avatar": "",
      "status": true,
      "lastActive": "2021-09-18T21:42:57Z"
    }, {
      "id": 5,
      "username": "ghanfrey4@geocities.jp",
      "otherName": "Gipsy",
      "lastName": "Hanfrey",
      "avatar": "https://robohash.org/etquisint.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-09-07T13:22:32Z"
    }, {
      "id": 6,
      "username": "clillyman5@nifty.com",
      "otherName": "Cole",
      "lastName": "Lillyman",
      "avatar": "",
      "status": false,
      "lastActive": "2022-01-16T13:16:57Z"
    }, {
      "id": 7,
      "username": "mbreckwell6@cnn.com",
      "otherName": "Miquela",
      "lastName": "Breckwell",
      "avatar": "https://robohash.org/doloresaconsequatur.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2022-04-10T02:31:07Z"
    }, {
      "id": 8,
      "username": "dineson7@ucoz.ru",
      "otherName": "Dyna",
      "lastName": "Ineson",
      "avatar": "",
      "status": true,
      "lastActive": "2021-09-29T19:23:06Z"
    }, {
      "id": 9,
      "username": "hclardge8@newyorker.com",
      "otherName": "Humbert",
      "lastName": "Clardge",
      "avatar": "https://robohash.org/omnisdoloresquas.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-11-21T10:09:40Z"
    }, {
      "id": 10,
      "username": "amilbank9@etsy.com",
      "otherName": "Annalee",
      "lastName": "Milbank",
      "avatar": "https://robohash.org/laboriosamnumquamaut.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2022-03-15T16:51:59Z"
    }, {
      "id": 11,
      "username": "cwheatcrofta@dell.com",
      "otherName": "Chicky",
      "lastName": "Wheatcroft",
      "avatar": "https://robohash.org/omnishicest.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2022-04-04T21:41:54Z"
    }, {
      "id": 12,
      "username": "hfranzolinib@mediafire.com",
      "otherName": "Hailee",
      "lastName": "Franzolini",
      "avatar": "https://robohash.org/quammagnamimpedit.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2022-01-30T15:54:03Z"
    }, {
      "id": 13,
      "username": "gcrippesc@mit.edu",
      "otherName": "Ginger",
      "lastName": "Crippes",
      "avatar": "https://robohash.org/istequaeratquo.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-10-30T02:58:20Z"
    }, {
      "id": 14,
      "username": "btrimmelld@booking.com",
      "otherName": "Bianca",
      "lastName": "Trimmell",
      "avatar": "https://robohash.org/eumenimaut.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-12-20T08:06:27Z"
    }, {
      "id": 15,
      "username": "xferriese@studiopress.com",
      "otherName": "Xerxes",
      "lastName": "Ferries",
      "avatar": "https://robohash.org/etfacerevoluptas.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-06-06T01:57:13Z"
    }, {
      "id": 16,
      "username": "gcampellif@privacy.gov.au",
      "otherName": "Gates",
      "lastName": "Campelli",
      "avatar": "https://robohash.org/quodistinctiovel.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-10-22T04:30:47Z"
    }, {
      "id": 17,
      "username": "blauxg@nifty.com",
      "otherName": "Bernadina",
      "lastName": "Laux",
      "avatar": "https://robohash.org/laborumquaeratdolor.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-09-01T11:41:10Z"
    }, {
      "id": 18,
      "username": "bmandrakeh@google.nl",
      "otherName": "Barrie",
      "lastName": "Mandrake",
      "avatar": "https://robohash.org/facilisdelenititotam.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-06-08T13:07:17Z"
    }, {
      "id": 19,
      "username": "ghammori@tinypic.com",
      "otherName": "Grantham",
      "lastName": "Hammor",
      "avatar": "https://robohash.org/quodaliquamut.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-10-06T11:09:47Z"
    }, {
      "id": 20,
      "username": "lrainardj@digg.com",
      "otherName": "Levin",
      "lastName": "Rainard",
      "avatar": "https://robohash.org/utquosed.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-06-04T01:41:08Z"
    }, {
      "id": 21,
      "username": "mhiddsleyk@exblog.jp",
      "otherName": "Millisent",
      "lastName": "Hiddsley",
      "avatar": "https://robohash.org/etnostrumcorrupti.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-07-28T04:43:42Z"
    }, {
      "id": 22,
      "username": "ggrestiel@clickbank.net",
      "otherName": "Giuseppe",
      "lastName": "Grestie",
      "avatar": "https://robohash.org/enimhicaut.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-10-11T20:42:56Z"
    }, {
      "id": 23,
      "username": "lrennenbachm@army.mil",
      "otherName": "Lauraine",
      "lastName": "Rennenbach",
      "avatar": "https://robohash.org/harumatenim.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-08-01T13:32:16Z"
    }, {
      "id": 24,
      "username": "iscarcen@archive.org",
      "otherName": "Iseabal",
      "lastName": "Scarce",
      "avatar": "https://robohash.org/veniamsimiliqueet.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-06-16T04:50:57Z"
    }, {
      "id": 25,
      "username": "sflanneryo@com.com",
      "otherName": "Sandor",
      "lastName": "Flannery",
      "avatar": "https://robohash.org/sitautexpedita.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2022-02-28T03:32:21Z"
    }, {
      "id": 26,
      "username": "jgerlackp@theatlantic.com",
      "otherName": "Jobie",
      "lastName": "Gerlack",
      "avatar": "https://robohash.org/teneturearumomnis.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-07-02T15:38:31Z"
    }, {
      "id": 27,
      "username": "fedbrookeq@tripod.com",
      "otherName": "Franciska",
      "lastName": "Edbrooke",
      "avatar": "https://robohash.org/ipsumeumqui.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-11-11T12:33:55Z"
    }, {
      "id": 28,
      "username": "kkohlermanr@omniture.com",
      "otherName": "Karlis",
      "lastName": "Kohlerman",
      "avatar": "https://robohash.org/inventoreetiusto.png?size=50x50&set=set1",
      "status": true,
      "lastActive": "2021-11-28T13:14:38Z"
    }, {
      "id": 29,
      "username": "bpumfretts@booking.com",
      "otherName": "Barton",
      "lastName": "Pumfrett",
      "avatar": "https://robohash.org/autvitaeet.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-05-13T10:41:42Z"
    }, {
      "id": 30,
      "username": "cberninit@hostgator.com",
      "otherName": "Christen",
      "lastName": "Bernini",
      "avatar": "https://robohash.org/abundesed.png?size=50x50&set=set1",
      "status": false,
      "lastActive": "2021-11-26T10:38:32Z"
    }]
  )
}
